### ISSUE TITLE
[Bug] brisk download file corrupted from upload.ee

### ISSUE THREAD

**Issue by ZorinFoss** [AminBhst/brisk#38]
Hi @AminBhst 

When download archive file from upload.ee, brisk download the file corrupted.

[sample](https://www.upload.ee/files/16217749/WindowsActivatorbyGoddy_4.9.7z.html)

**Comment by AminBhst** [comment]
Weird. I'll look into it

**Comment by AminBhst** [comment]
@ZorinFoss I tried downloading this link a couple times and for some reason the link pointed to an HTML instead of the file itself. That's why the file was corrupted. It was actually the bytes of an HTML in a compressed format, therefore, the file couldn't be opened. Today I tried again and it worked fine and couldn't reproduce this issue anymore.

**Comment by ZorinFoss** [comment]
It's the VPN cause the problem and it works now. thank you @AminBhst
