### ISSUE TITLE
Duplicated download finish signal

### ISSUE THREAD

**Issue by Norman-w** [AminBhst/brisk#4]
When downloading a smaller file. It will get progress like below
flutter: Received progress update: 0.0
flutter: Received progress update: 0.0
flutter: Received progress update: 0.0
flutter: Received progress update: 0.0
flutter: Received progress update: 0.0
flutter: Received progress update: 0.0
flutter: Received progress update: 0.0
flutter: Received progress update: 1.0
flutter: Received progress update: 1.0

we got 2 or more 1.0(finish signal)
so we can't show a notification correctly

**Comment by AminBhst** [comment]
@Norman-w Do you mean that you receive duplicate download completion signals which result in duplicate desktop notifications?
If that's the case, that is an issue I'm aware of and will definitely work on it for the next version. The next version of Brisk is gonna have relatively big changes, namely migrating the database to hive and implementing download queues. I will most likely release it in the following weeks and when I do, I will let you know in this issue so you can work on it when the bug is fixed. Thank you for reminding me of this issue.

**Comment by AminBhst** [comment]
@Norman-w Do you mean that you receive duplicate download completion signals which result in duplicate desktop notifications?
If that's the case, that is an issue I'm aware of and will definitely work on it as soon as I can. I will let you know in this issue when it's fixed in the developer branch. Thank you for reminding me of this issue

**Comment by Norman-w** [comment]
> @Norman-w Do you mean that you receive duplicate download completion signals which result in duplicate desktop notifications? If that's the case, that is an issue I'm aware of and will definitely work on it as soon as I can. I will let you know in this issue when it's fixed in the developer branch. Thank you for reminding me of this issue

Yes, wait good news

**Comment by AminBhst** [comment]
@Norman-w This bug is now fixed on the developer branch. I have only tested it on windows. Could you also test it on macOS and let me know if it's works correctly so that I can close this issue?

**Comment by Norman-w** [comment]
You did a great job.
