### ISSUE TITLE
Does not compile on Flutter >=3.23

### ISSUE THREAD

**Issue by pluiedev** [AminBhst/brisk#71]
Ditto. With certain Linux package repositories removing support for Flutter 3.22 (e.g. Nixpkgs), Brisk is currently unbuildable (see logs below):
```console
brisk> [        ] [+3324 ms] /nix/store/r3ayvkk64d6bpyn1j2jv65yrcmgfwmvi-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1915:39: Error: Method not found: 'SchemeRainbow'.
brisk> [        ] [   +1 ms]       DynamicSchemeVariant.rainbow => SchemeRainbow(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
brisk> [        ] [        ]                                       ^^^^^^^^^^^^^
brisk> [        ] [        ] /nix/store/r3ayvkk64d6bpyn1j2jv65yrcmgfwmvi-flutter-sdk-flutter/lib/src/material/color_scheme.dart:1916:42: Error: Method not found: 'SchemeFruitSalad'.
brisk> [        ] [        ]       DynamicSchemeVariant.fruitSalad => SchemeFruitSalad(sourceColorHct: sourceColor, isDark: isDark, contrastLevel: contrastLevel),
brisk> [        ] [        ]
```

It appears that updating Flutter SDK and other dependencies would solve the issue.
See similar issues at https://github.com/NixOS/nixpkgs/issues/341893, https://github.com/NixOS/nixpkgs/pull/331290#issuecomment-2426384931

**Comment by AminBhst** [comment]
Hey. I don't have a NixOS setup myself so I can't currently reproduce this. There are some dependencies like window_manager that might break Brisk if I upgrade Flutter to the latest version. At least this was the case the last time I checked, and it may have been fixed already.
I will try to see whether or not I can upgrade to the latest Flutter version without breaking anything. But I imagine you could still build brisk if you download the Flutter SDK binary from the [SDK archives](https://docs.flutter.dev/release/archive).

**Comment by AminBhst** [comment]
@pluiedev I've updated the pubspec.yaml file to support Flutter SDK from version 3.22 to the latest version (2.27.1). I have also tested the build process and it worked fine.
There is one point I'd like to mention here though if you plan on building Brisk from source. Brisk comes with a separate module which is essentially another Flutter project called [brisk_auto_updater](https://github.com/AminBhst/brisk/tree/main/brisk_auto_updater). If the automatic update feature of Brisk is planned to be supported (Clicking on check for update leading to brisk automatically downloading the latest version and replacing the old files), the brisk_auto_updater module needs to also be built and its content inside the `bundle` directory should be copied to a directory inside of the root build folder called `updater`. You can download the linux .tar.gz release to see how the directory structure looks like. 
However, due to the difficulty of handling elevated permission requirements properly in Linux, the updater module fails to replace the old files if Brisk's installation directory is in a location that requires elevated permissions. I'm not familiar with NixOS, so if packages on NixOS are always installed inside a directory with elevated permission requirement, it probably wouldn't make sense to bundle it anyway since the updater wouldn't work.
